name: Terraform-Validation

on:
  push:
    branches: 
    - '!master'
    - '!release'
    - '!dev'

defaults:
  run:
    working-directory: project/deployments

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    name: Validates Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        id: fmt
        run: echo Checking Terraform Format
        run: terraform fmt -check
      - name: Terraform init
        id: init
        run: echo Initializing Terraform
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: echo Validating Terraform
        run: terraform validate
        