name: Terraform-Validation

on:
  push:
    branches-ignore: 
    - 'master'
    - 'release'

defaults:
  run:
    working-directory: project/deployments

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    name: Validates Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        env:
          AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION=us-west-2
        run: terraform plan -var-file="dev.tfvars"
        